site_name: FabMaMiCo
site_description: An automation toolkit for the MaMiCo framework

repo_url: https://github.com/HSU-HPC/FabMaMiCo
repo_name: HSU-HPC/FabMaMiCo

copyright: Johannes Michaelis, Piet Jarmatz, Derek Groen, Philipp Neumann, Olaf Schenk

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# plugins:
# - open-in-new-tab

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Machine Configuration:
    - General: machine-configuration/general.md
    - Parameters: machine-configuration/parameters.md
    - Examples: machine-configuration/examples.md
  - Simulation Setups: setup-simulations.md
  - FabSim Commands: fabsim-commands.md
  - FabMaMiCo Commands: fabmamico-commands.md
