mamico_branch_tag_commit: 8e4f0ec8f1977c6ef95015bb062c3e59c0389c5e

need_ls1: no

cmake_flags_mamico:
  # BUILD_TESTING: off
  # BUILD_WITH_ADIOS2: off
  # BUILD_WITH_EIGEN: off
  # BUILD_WITH_LAMMPS: off
  BUILD_WITH_MPI: on
  # BUILD_WITH_OPENFOAM: off
  # BUILD_WITH_PINT_DEBUG: off
  # BUILD_WITH_PRECICE: off
  # BUILD_WITH_PYBIND11: off
  CMAKE_BUILD_TYPE: "DebugOptimized"
  # CMAKE_INSTALL_PREFIX: "/usr/local"
  # MDDim: "MDDim3"
  MD_SIM: "SIMPLE_MD"
