mamico_branch_tag_commit: master

need_eigen: on
need_mpi: on
need_ls1: on
need_pybind11: on
need_ls1: on
ls1_branch_tag_commit: Joshua

#############################################################################

########################
## MaMiCo Compilation ##
########################
build_testing: off                  # [on, off]
build_with_adios2: off              # [on, off] no
build_with_eigen: off               # [on, off] yes
build_with_lammps: off              # [on, off] no
build_with_mpi: off                 # [on, off] yes
build_with_openfoam: off            # [on, off] no
build_with_pint_debug: off          # [on, off]
build_with_precice: off             # [on, off] no
build_with_pybind11: off            # [on, off] yes

cmake_build_type: DebugOptimized    # [Debug, DebugMD, DebugOptimized, RelWithDebInfo, Release]
cmake_install_prefix: /usr/local    # string (optional)
compiletest_compilers: g++ clang++  # string
compiletest_modes: Debug DebugOptimized, RelWithDebInfo, Release
enable_coverage: off                # [on, off]
mddim: MDDim3                       # [MDDim2, MDDim3]
md_sim: SIMPLE_MD                   # [SIMPLE_MD, LAMMPS_MD, LAMMPS_DPD, LS1_MARDYIN]
use_collective_mpi: off             # [on, off]
