mamico_branch_tag_commit: master               # [<branch-name> or <tag> or <commit>]

need_ls1: no
ls1_branch_tag_commit: 6032ae49ad742f9bd595b7b83da38b6bb65b35a4                 # [<branch-name> or <tag> or <commit>]

cmake_flags_mamico:
  # BUILD_TESTING: off
  # BUILD_WITH_ADIOS2: off
  # BUILD_WITH_EIGEN: off
  # BUILD_WITH_LAMMPS: off
  BUILD_WITH_MPI: on
  # BUILD_WITH_OPENFOAM: off
  # BUILD_WITH_PINT_DEBUG: off
  # BUILD_WITH_PRECICE: off
  # BUILD_WITH_PYBIND11: off
  # CMAKE_BUILD_TYPE: "Release"
  # CMAKE_INSTALL_PREFIX: "/usr/local"
  # MDDim: "MDDim3"
